POST http://localhost:8080/api/produto
Content-Type: application/json

{
  "codigo":"321A",
  "descricao": "produto_X",
  "valor": 11.8
}

###

GET http://localhost:8080/api/produto/321A
Accept: application/json

###

PUT http://localhost:8080/api/produto
Content-Type: application/json

{
  "codigo":"321A",
  "descricao": "produto_XYZ",
  "valor": 15.8
}

###

DELETE http://localhost:8080/api/produto/321A

###

###

GET http://localhost:8080/api/produto
Accept: application/json

###
